### ISSUE TITLE
P3: Notification

### ISSUE THREAD

**Issue by Eyskha** [fund-team/fund2#8]
Core CI feature 3
The CI server supports notification of CI results. At least one notification mechanism of the following list is implemented:

- Commit status: the CI server sets the commit status (https://help.github.com/articles/about-statuses/) on the repository (REST API https://developer.github.com/v3/repos/statuses/ for Github)
- Email: the CI server sends an email to the project member about the build result.

Preparation: The students document in the README how notification has been implemented and unit-tested.

Assessment: The grader observes the status of the change made while assessing P2. Optionally, the grader may look at the implementation or the tests of this feature.

**Comment by leddy231** [comment]
try commit status, optinally discord webhook
